name: Sync Spotify Liked Songs

on:
  schedule:
    - cron: '0 */12 * * *' # run every 12 hours
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install spotipy

      - name: Run sync script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          # Recreate the cache from secrets
          echo '${{ secrets.SPOTIPY_CACHE }}' > .cache
          python run.py

      - name: Save updated Spotify cache back to Secrets
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} 
        run: |
          # Update the secret with the newly refreshed .cache file
          gh secret set SPOTIPY_CACHE < .cache